# 所有环境的共享默认配置
default: &default
  # adapter: postgresql          # 指定适配器为 PostgreSQL
  # encoding: unicode            # 使用 Unicode 编码
  # host: localhost              # PostgreSQL 服务器地址（默认本地）
  # port: 5432                   # PostgreSQL 默认端口
  # username: postgres    # 替换为你的 PostgreSQL 用户名
  # password: pw19952013    # 替换为密码（生产环境建议用环境变量）
  # pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>  # 连接池大小
  # timeout: 5000                # 连接超时时间（毫秒）

# 开发环境配置
development:
  <<: *default                 # 继承默认配置
  database: policy_development  # 开发数据库名（通常为项目名_development）
  # 可选：禁用连接复用（开发时避免缓存问题）
  reaping_frequency: nil
  prepared_statements: false

# 测试环境配置
test:
  <<: *default
  database: policy_test      # 测试数据库名
  # 测试环境推荐禁用预处理语句加速测试
  prepared_statements: false

# 生产环境配置（安全关键！）
production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>  # 直接使用Render提供的连接字符串
  # 生产环境推荐启用连接池和预处理语句
  pool: 25                     # 根据服务器并发调整
  prepared_statements: true
  # 可选：SSL 加密连接（云数据库必备）
  sslmode: require  # Render数据库强制SSL但无需证书验证
  sslrootcert: <%= ENV['DB_SSL_CERT_PATH'] || '/etc/ssl/certs/ca-certificates.crt' %>